# Project/MCU configuration
NAME:=libminiavr
MCU:=atmega328p
BOARD:=ARDUINO_AVR_UNO
F_CPU:=16000000
SRCS:=src/gpio.c src/usart.c

# Autogenerated
DEPS:=$(SRCS:.c=.o)
BIN:=$(NAME).a

# Toolchain
CC:=avr-gcc
AR:=avr-ar
OBJCOPY:=avr-objcopy

CFLAGS:=-mmcu=$(MCU) -D$(BOARD) -DF_CPU=$(F_CPU) -Os

.PHONY all: $(BIN)

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $< -Iinclude

$(BIN): $(DEPS)
	$(AR) rcs $@ $(DEPS)

clean:
	rm -f $(DEPS)
	rm -f $(BIN)
