# Project/MCU configuration
NAME:=loragram
MCU:=atmega328p
BOARD:=ARDUINO_AVR_UNO
F_CPU:=16000000
SRCS:=$(shell find src -name "*.c")
PORT:=/dev/ttyUSB0

# Library
LIBRARY_CFLAGS:=-Ilibminiavr/include -Llibminiavr -lminiavr

# Autogenerated
DEPS:=$(SRCS:.c=.o)
BIN:=$(NAME).elf
HEX:=$(BIN:.elf=.hex)

# Toolchain
CC:=avr-gcc
OBJCOPY:=avr-objcopy

# AVRdude settings
PROGRAMMER:=arduino
PARTNO:=$(MCU)

include libminiavr/board.inc

CFLAGS:=-mmcu=$(MCU) -D$(BOARD) -DF_CPU=$(F_CPU) -Os -Wall

.PHONY all: checklibrary $(HEX)

checklibrary:
	if [ ! -f "libminiavr/libminiavr.a" ]; then echo "Please compile libminiavr by running make in libminiavr/ first"; exit 1; fi

%.o: %.c
	$(CC) $(CFLAGS) -o $@ -c $< $(LIBRARY_CFLAGS)

$(BIN): $(DEPS)
	$(CC) $(CFLAGS) $(DEPS) -o $@ $(LIBRARY_CFLAGS)

$(HEX): $(BIN)
	$(OBJCOPY) -R .eeprom -O ihex $< $@

upload: $(HEX)
	avrdude -c $(PROGRAMMER) -p $(PARTNO) -P $(PORT) $(AVRDUDE_EXTRA) -U flash:w:$<

clean:
	rm -f $(DEPS)
	rm -f $(BIN)
	rm -f $(HEX)
